#!/usr/bin/env ruby

require "logger"
require "bundler"
Bundler.require :default, :development

def connect!(config = {})
  Clickhouse.logger = Logger.new(STDOUT)
  Clickhouse.establish_connection(config)
end

def conn(config = {})
  connect!(config) unless Clickhouse.connection
  Clickhouse.connection
end

def logs
  "logs_test"
end

def create_table
  conn.create_table(logs) do |t|
    t.fixed_string :id, 16
    t.uint16       :year
    t.date         :date
    t.date_time    :time
    t.string       :event
    t.uint32       :user_id
    t.float32      :revenue
    t.engine       "MergeTree(date, (year, date), 8192)"
  end
end

puts "Loading Clickhouse development environment (#{Clickhouse::VERSION})"
Pry.start
