#!/usr/bin/env ruby

require "logger"
require "bundler"
Bundler.require :default, :development

def connect!(config = {})
  Clickhouse.establish_connection(config)
  Clickhouse.logger = Logger.new(STDOUT)
  nil
end

puts "Loading Clickhouse development environment (#{Clickhouse::VERSION})"
Pry.start
